# Generated by Django 5.1.7 on 2025-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', '未着手'), ('DOING', '進行中'), ('DONE', '完了')], default='TODO', max_length=5, verbose_name='ステータス'),
        ),
    ]
